# Generated by Django 5.2 on 2025-04-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beat',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='beat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
