# Generated by Django 5.2 on 2025-04-29 09:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_bundle_options_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='beats/audio/'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beats/images/'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.beat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'beat')},
            },
        ),
    ]
