# Generated by Django 5.2 on 2025-04-30 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.bundle'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='beat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.beat'),
        ),
    ]
